### ISSUE TITLE
libcrypto.so.1.1.0 not found

### ISSUE THREAD

**Issue by tpj** [cryptobiu/scapi#70]
Following the installation instructions on http://scapi.readthedocs.org/en/latest/install.html
(except that I checked out `SCAPI-V2-3-0` instead of the current head) I get the following exception when running the sample program DlogExample.java from http://scapi.readthedocs.org/en/latest/quickstart.html

```
tpj@ubuntu:~$ scapic DlogExample.java
tpj@ubuntu:~$ scapi DlogExample
Exception in thread "main" java.lang.UnsatisfiedLinkError: /usr/local/lib/scapi/libOpenSSLJavaInterface.so: libcrypto.so.1.1.0: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1880)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at edu.biu.scapi.primitives.dlog.openSSL.OpenSSLAdapterDlogEC.<clinit>(OpenSSLAdapterDlogEC.java:129)
	at DlogExample.main(DlogExample.java:16)
```

After following the installation procedure I have the following libraries:

```
tpj@ubuntu:~/scapi$ sudo find / -name *libcrypto*
/usr/lib/vmware-tools/lib64/libcrypto.so.0.9.8
/usr/lib/vmware-tools/lib64/libcrypto.so.0.9.8/libcrypto.so.0.9.8
/usr/lib/vmware-tools/lib32/libcrypto.so.0.9.8
/usr/lib/vmware-tools/lib32/libcrypto.so.0.9.8/libcrypto.so.0.9.8
/home/tpj/scapi/build/CryptoPP/libcryptopp.so
/home/tpj/scapi/build/CryptoPP/libcryptopp.a
/home/tpj/scapi/build/OpenSSL/libcrypto.pc
/home/tpj/scapi/build/OpenSSL/libcrypto.so.1.1.0
/home/tpj/scapi/build/OpenSSL/libcrypto.a
/home/tpj/scapi/build/OpenSSL/libcrypto.so
/home/tpj/scapi/install/lib/libcryptopp.so
/home/tpj/scapi/install/lib/libcryptopp.a
/home/tpj/scapi/install/ssl/lib/pkgconfig/libcrypto.pc
/home/tpj/scapi/install/ssl/lib/libcrypto.so.1.1.0
/home/tpj/scapi/install/ssl/lib/libcrypto.a
/home/tpj/scapi/install/ssl/lib/libcrypto.so
/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
```

Looks to me as if the libcrypto.so.1.1.0 is created correctly by running `make`, but somehow does not get installed  properly by running

    sudo make install prefix=/usr

I experience this issue on Ubuntu 14.04 LTS 64-bit (running in VMWare).

**Comment by AsafKleinbort** [comment]
Problem was that ssl was installed to different directory.
Fixed the instructions to use the prefix both in `make` and in `make install`.
Together with the fix for #69: building from master/HEAD and running the example in the quick-start guide works now.
